# Generated by Django 5.0.6 on 2025-02-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("listing_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accommodates", models.IntegerField()),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bedrooms",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "beds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                ("host_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("host_url", models.TextField()),
                ("host_name", models.TextField()),
                ("host_since", models.DateField()),
                ("host_location", models.TextField(blank=True, null=True)),
                ("host_about", models.TextField(blank=True, null=True)),
                ("host_response_time", models.TextField(blank=True, null=True)),
                ("host_response_rate", models.FloatField(blank=True, null=True)),
                ("host_acceptance_rate", models.FloatField(blank=True, null=True)),
                ("host_is_superhost", models.BooleanField()),
                ("host_thumbnail_url", models.TextField()),
                ("host_picture_url", models.TextField()),
                ("host_neighbourhood", models.TextField(blank=True, null=True)),
                ("host_listings_count", models.IntegerField()),
                ("host_total_listings_count", models.IntegerField()),
                ("host_verifications", models.TextField()),
                ("host_has_profile_pic", models.BooleanField()),
                ("host_identity_verified", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Neighbourhood",
            fields=[
                (
                    "neighbourhood_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("neighbourhood", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="airbnb_data_hub_dc.listing",
                    ),
                ),
                ("has_availability", models.BooleanField()),
                ("availability_30", models.IntegerField()),
                ("availability_60", models.IntegerField()),
                ("availability_90", models.IntegerField()),
                ("availability_365", models.IntegerField()),
                ("calendar_last_scraped", models.DateField()),
                ("instant_bookable", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ListingCategorical",
            fields=[
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="airbnb_data_hub_dc.listing",
                    ),
                ),
                ("listing_name", models.TextField()),
                ("hover_description", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("listing_url", models.TextField()),
                ("neighborhood_overview", models.TextField(blank=True, null=True)),
                ("picture_url", models.TextField()),
                ("property_type", models.TextField()),
                ("room_type", models.TextField()),
                ("amenities", models.TextField()),
                ("bathrooms_text", models.TextField(blank=True, null=True)),
                ("license", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ListingReviews",
            fields=[
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="airbnb_data_hub_dc.listing",
                    ),
                ),
                ("number_of_reviews", models.IntegerField()),
                ("number_of_reviews_ltm", models.IntegerField()),
                ("number_of_reviews_l30d", models.IntegerField()),
                ("first_review", models.DateField(blank=True, null=True)),
                ("last_review", models.DateField(blank=True, null=True)),
                (
                    "review_scores_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "review_scores_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "review_scores_cleanliness",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "review_scores_checkin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "review_scores_communication",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "review_scores_location",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "reviews_per_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "review_scores_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinMaxNight",
            fields=[
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="airbnb_data_hub_dc.listing",
                    ),
                ),
                ("minimum_nights", models.DecimalField(decimal_places=2, max_digits=5)),
                ("maximum_nights", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "minimum_minimum_nights",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "maximum_minimum_nights",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "minimum_maximum_nights",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "maximum_maximum_nights",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "minimum_nights_avg_ntm",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "maximum_nights_avg_ntm",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("available", models.BooleanField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("minimum_nights", models.IntegerField()),
                ("maximum_nights", models.IntegerField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airbnb_data_hub_dc.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HostListingsCount",
            fields=[
                (
                    "host",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="airbnb_data_hub_dc.host",
                    ),
                ),
                ("host_listings_total_count", models.IntegerField()),
                ("host_listings_entire_homes_count", models.IntegerField()),
                ("host_listings_private_rooms_count", models.IntegerField()),
                ("host_listings_shared_rooms_count", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="airbnb_data_hub_dc.host",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="neighbourhood",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="airbnb_data_hub_dc.neighbourhood",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("review_date", models.DateField()),
                ("reviewer_id", models.BigIntegerField()),
                ("reviewer_name", models.TextField(blank=True, null=True)),
                ("review_comments", models.TextField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airbnb_data_hub_dc.listing",
                    ),
                ),
            ],
        ),
    ]
