# Generated by Django 5.0.6 on 2025-02-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airbnb_data_hub_dc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
