# Generated by Django 5.0.6 on 2025-02-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airbnb_data_hub_dc", "0003_alter_minmaxnight_minimum_nights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minmaxnight",
            name="minimum_nights",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
