# Generated by Django 5.0.6 on 2025-02-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airbnb_data_hub_dc", "0006_alter_minmaxnight_minimum_nights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minmaxnight",
            name="minimum_nights",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
    ]
